### ISSUE TITLE
Not Able to generate API key !

### ISSUE THREAD

**Issue by Inaya791** [recallai/meeting-action-items-bot#1]
As i am signed up with this link(https://dash.readme.com/to/recallai/signup)
And then to create API key wit this link(https://us-west-2.recall.ai/dashboard/)
Not able to generate it says wrong E-mail and Password ,when i am resetting the password not getting any E-mail also.
Please assist me ASAP.

**Comment by TimeToogo** [comment]
Hey @Inaya791,
Sorry for the confusion here, it appears you are trying to sign up to readme.com which is the platform we use for our docs. Please fill out our [get started](https://www.recall.ai/get-started?utm_source=github) form to get access to the recall platform.

**Comment by Inaya791** [comment]
Hello  TimeToogo,
I tried to register with my work E-mail ,but i didn't find the procedure of signing up that i can login for API dashboard.
The link which you shared above its only for registering conference only.
I need to try out this Repo so i need to generate APIs of recall.ai 
Please Assist me ASAP

**Comment by tamagoeggo** [comment]
Hey @Inaya791, you will have to chat with a member of our team to get an API key, so the link @TimeToogo sent above is correct!
